### ISSUE TITLE
Rückfrage Data-Sheet Philips PLN2033

### ISSUE THREAD

**Issue by gordenNom** [Smart-Minotaur/Smart-Minotaur.github.io#1]
Hallo,
ich weiß leider nicht wie ich euch anders erreichen kann...
Ich habe gesehen das Ihr den Mouse Sensor Philips PLN2033 verwendet habt. Anscheinend habt Ihr das Data-Sheet zu dem Sensor gehabt. Ich habe im ganzen Internet keins gefunden. Könnt ihr mir sagen wo Ihr das Datenblatt her hattet oder hab ich noch eins?
Zweite Frage habt Ihr den Sensor einzeln gekauft oder aus einer alten Maus ausgebaut?
Ich wäre euch sehr dankbar benötige diese Antwort für eine Studienarbeit!
Grüße
Gorden

**Comment by Rookfighter** [comment]
Hi @gordenNom 
auf GitHub sind wir immer erreichbar, auch wenn ein Issue ein merkwürdiger Kommunikationskanal ist :p.
**Zu deiner ersten Frage:** Das Datasheet haben wir direkt bei Philips angefragt und haben es auch bekommen. Wir haben dabei natürlich angemerkt, dass es sich um ein studentisches Projekt handelt, daher kann es sein, dass sie das Datasheet nicht für private Projekte vergeben, aber das weiß ich nicht. @JeGa du hast Philips doch angeschrieben, oder? Hast du die Mail noch oder weißt du noch an welche Addresse du das geschickt hast?
**Zu deiner zweiten Frage:** Ja wir haben den Sensor aus Gaming Mäusen ausgebaut. @JeGa weißt du noch welches Modell das war? Funfact: Bei der Anfrage an Philips wegen dem Datasheet haben sie uns auch gleich angeboten Sensoren bei ihnen zu kaufen, die mindest Anzahl war aber 1000 Stück. Also haben wir dankend abgelehnt.
Ich hoffe ich konnte dir ein bisschen helfen :), @JeGa wird sicher auch noch etwas zu sagen haben.

**Comment by JeGa** [comment]
Hi Gorden,
auf der Produkt Homepage für den Sensor sollte es eine E-Mail Adresse geben.
Dort einfach mal anfragen ...
Grüße
JeGa

**Comment by gordenNom** [comment]
Vielen Dank für eure schnelle Info. Ich habe Sie mal angeschrieben.
